dist: trusty
sudo: required

language: node_js
node_js:
  - 8

branches:
  only:
  - master
  
jobs:
  include:
    - stage: unit tests
      script: echo one
    - stage: unit tests
      script: echo two
