dist: trusty
sudo: required

language: node_js
node_js:
  - 8

branches:
  only:
  - master

jobs:
  include:
    - stage: test1
    - script: echo "Test Completed Successfully"
    - stage: deploy
    - script: echo "Deployed"
